Clean up uiflag.txt
blizzhackers/kolbot pull request #270
Opened 2021-09-09 20:27 UTC by jtrumbull

2022-03-03 15:13 UTC, theBGuy requested changes
See comments, everything else looks good

2022-03-03 15:13 UTC, theBGuy commented on d2bs/kolbot/sdk/uiflag.txt
> +0x10    ? Assume help button visible
0x10 is Key to the Cairn Stones Screen

2022-03-03 15:13 UTC, theBGuy commented on d2bs/kolbot/sdk/uiflag.txt
> +0x02	Character screen open
0x02 the original statement Character Stat screen is clearer than Character Screen

2022-03-08 01:05 UTC, theBGuy approved these changes

2022-03-08 01:06 UTC, merged

2022-03-08 01:22 UTC, jtrumbull commented
Wonderful