Bloodraven smith quest
blizzhackers/kolbot pull request #392
Opened 2023-12-10 19:46 UTC by icommitdesnet

2023-12-10 20:35 UTC, theBGuy requested changes
Add the level check for smith, other than that. Good work

2023-12-10 20:35 UTC, theBGuy commented on d2bs/kolbot/libs/systems/autorush/AutoRush.js
> +    log("starting smith");
Smith can't be completed if the players level is < 8

2023-12-11 20:25 UTC, icommitdesnet commented on d2bs/kolbot/libs/systems/autorush/AutoRush.js
> +    log("starting smith");
added lvl check for requesting nick

2023-12-11 22:32 UTC, theBGuy approved these changes

2023-12-11 22:41 UTC, merged